server:
  port: 9003
  use-forward-headers: true
  forward-headers-strategy: framework

spring:
  application:
    name: FEIGN-CLIENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost