server:
  port: 9004

spring:
  application:
    name: CUSTOMER-SERVICE
  mvc:
    path match:
      matching-strategy: ant_path_matcher


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost